#!/bin/bash

case "$1" in
     configure)
        mysql --defaults-file=/etc/alternc/my.cnf -e "INSERT INTO domaines_type
(name, description, target, entry, compatibility, enable, only_dns, need_dns, advanced, create_tmpdir, create_targetdir, has_https_option) VALUES
('wsgi', 'Locally hosted (WSGI Python3)', 'DIRECTORY', '%SUB% IN A @@PUBLIC_IP@@',
'txt,defmx,defmx2,mx,mx2', 'ALL', 0, 0, 1, 1, 1, 1),
('wsgi-both', 'WSGI Python3 (HTTP + HTTPS)', 'DIRECTORY', '%SUB% IN A @@PUBLIC_IP@@',
'txt,defmx,defmx2,mx,mx2', 'NONE', 0, 0, 1, 1, 1, 0),
('wsgi-http', 'WSGI Python3 (HTTP)', 'DIRECTORY', '%SUB% IN A @@PUBLIC_IP@@',
'txt,defmx,defmx2,mx,mx2', 'NONE', 0, 0, 1, 1, 1, 0),
('wsgi-https', 'WSGI Python3 (HTTPS)', 'DIRECTORY', '%SUB% IN A @@PUBLIC_IP@@',
'txt,defmx,defmx2,mx,mx2', 'NONE', 0, 0, 1, 1, 1, 0);
"